# Ci workflow to be triggered for every pull-request and push
name: "CI"

on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: /opt/python38/bin/python3
          - os: windows-latest
            python: C:\Python38\python.exe
    runs-on: ['${{matrix.os}}']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install ittapi
        run:
          cd ittapi/python
          python3 -m pip install .

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: /opt/python38/bin/python3
          - os: windows-latest
            python: C:\Python38\python.exe
    runs-on: ['${{matrix.os}}']
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: run unit-test
        run:
          cd ittapi/python
          python3 -m unittest discover -s utest -t utest
