name: ITT_API_REL

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

        steps:
          - name: checkout sources
          - uses: actions/checkout@v4

            # Used to host cibuildwheel
          - name: setup python version
          - uses: actions/setup-python@v5

          - name: Install cibuildwheel
            run: python -m pip install cibuildwheel==2.20.0

          - name: Build wheels
            run: |
              cd python
              python -m cibuildwheel --output-dir wheelhouse
              # to supply options, put them in 'env', like:
              # env:
              #   CIBW_SOME_OPTION: value

          - uses: actions/upload-artifact@v4
            with:
              name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
              path: ./wheelhouse/*.whl
